import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "react-hot-toast"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Leaf | Cursos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="min-h-screen">
              <Navbar />

              <main className="py-0">
                {/* Removido o container e padding para permitir conteúdo full-width */}
                <div className="w-full">
                  <div className="w-full">
                    {/* Sidebar commented out */}
                    {/* <div className="hidden lg:block lg:col-span-3">
                      Sidebar
                    </div> */}
                    <div className="w-full">
                      {/* Content full width - sem centralização forçada */}
                      <div className="w-full">
                        {children}
                      </div>
                    </div>
                  </div>
                </div>
              </main>
            </div>
           <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}